#!/usr/bin/env bash
# Configures Nginx server to redirect to another page.
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
new_string = "server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx start
