#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Create directory for web files
sudo mkdir -p /var/www/html

# Change permissions to allow easy file creation
sudo chmod -R 755 /var/www

# Create index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to add custom header and redirect
custom_header_string="add_header X-Served-By \$hostname;"
redirect_string="rewrite ^/redirect_me google.com permanent;"
sudo sed -i "s/# server_name _;/server_name _;\n\t$custom_header_string\n\t$redirect_string/" /etc/nginx/sites-enabled/default

# Configure Nginx to handle 404 errors
error_page_string="error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal; }"
sudo sed -i "s/# listen 80 default_server;/listen 80 default_server;\n\t$error_page_string/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
