#!/usr/bin/env bash
# a configuration to connect to a server without typing a password.
Host 517721-web-01
    HostName 100.26.158.239
    User ubuntu
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
