#!/usr/bin/env bash
# a configuration to connect to a server without typing a password.
Host 517721-web-01
    HostName 54.237.40.228
    User ubuntu
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
